
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
 

export const FETCH_AVAILABLE_FILM_START = 'FETCH_AVAILABLE_FILM_START';
export const FETCH_AVAILABLE_FILM_SUCCESS = 'FETCH_AVAILABLE_FILM_SUCCESS';
export const FETCH_AVAILABLE_FILM_FAIL = 'FETCH_AVAILABLE_FILM_FAIL';
export const RENTFILM_INIT = 'RENTFILM_INIT';